### ISSUE TITLE
Installation error with xbuild on Mac OS Sierra (10.12.2)

### ISSUE THREAD

**Issue by apjmason** [reinterpretcat/utymap#114]
Thanks for what looks like a great library.  I'm trying to install it on Mac OS 10.12.2 following the instructions in the wiki and everything went fine until I got the this step: `xbuild /p:Configuration=Release UtyMap.Unity.sln` which gives me a "command not found" error.  

I'm fairly new to Unity development, but have successfully built for iOS before.  I'm using Unity 5 and suspect this has something to do with recent changes in Mono support, but was unable to find a fix after poking around the usual forums.  

I know this is more an issue with my system than your library, but would be grateful for any suggestions.

**Comment by reinterpretcat** [comment]
> which gives me a "command not found" error.

Could you check whether _xbuild_ command is installed? Just run it without any arguments. The second option is to use Utymap.Unity.dll from the latest version as there was no changes in master on top (I'm working on major update in separate branch). You can download it from release page.

**Comment by apjmason** [comment]
That was the issue, I couldn't find xbuild.  Eventually did and fixed it with `export PATH="/Applications/Unity/Unity.app/Contents/Mono/bin:$PATH"`

But when I ran the xbuild command the build failed and the compiler crashed with code: 1 (see log attached).  

Thanks for your help
[utymap_build_errors.txt](https://github.com/reinterpretcat/utymap/files/735935/utymap_build_errors.txt)

**Comment by reinterpretcat** [comment]
It looks like there is a problem with Unity's dlls which are committed to repository. Probably, you have different Unity version and this causes compiler fail: 

>The following assembly referenced from /Users/Austin 1/Unity/Plugins/utymap/unity/library/packages/UnityEditor.dll could not be loaded:
>Assembly:   ICSharpCode.NRefactory    (assemblyref_index=11)

There are couple possibilities:
1. you can try to replace unity's libraries with dlls from you unity installation folder.
2. you can just copy all cs files used by UtyMap.Unity.csproj to demo project folder as regular unity's scripts. Then they will be compiled automatically by Unity. Some minor things might happen due to compiler differences but it should be fixable.
3. Just use dll from last release

**Comment by reinterpretcat** [comment]
Assume that problem is solved
